[platformio]
default_envs = receiver-node, emitter-node

[env:base]
platform = espressif8266
board = esp8285
framework = arduino
monitor_speed = 115200
build_src_filter = +<*> -<get_mac/>
lib_deps =
    crankyoldgit/IRremoteESP8266

[env:receiver-node]
extends = env:base
build_flags =
    -D NODE_ROLE=ROLE_RECEIVER

[env:emitter-node]
extends = env:base
build_flags =
    -D NODE_ROLE=ROLE_EMITTER

; Flash this to a device to print its MAC address (used during initial setup)
[env:get-mac]
extends = env:base
build_src_filter = -<*> +<get_mac/>

[env:native]
platform = native
build_flags =
    -D UNIT_TEST

[env:native-coverage]
platform = native
build_flags =
    -D UNIT_TEST
    -fprofile-arcs
    -ftest-coverage
    -O0
extra_scripts = scripts/gcov_link_flags.py
